Repository newsviz/newsviz, pull requests merged in 2020-10, with the labels that each got.

#13 get_fnames
  CONTRIBUTING.md
  newsviz/pipeline.py
Labels: ROADMAP

#12 README.md translation
  CONTRIBUTING.md
  README.md
Labels: documentation

#18 Сохранение словаря BigARTM
  newsviz/topic_model.py
Labels: hacktoberfest-accepted

#17 Replaced preprocessing script
  newsviz/preprocessing_tools.py
Labels: hacktoberfest-accepted

#23 Путь к файлам для визуализации как параметр.
  .gitignore
  config/config.ini
  newsviz/visualizer/app.py
  newsviz/visualizer/utils.py
Labels: ROADMAP, hacktoberfest-accepted

#24 add bump chart
  newsviz/visualizer/utils.py
Labels: ROADMAP, hacktoberfest-accepted

#25 Template classifier
  .gitignore
  config/config.ini
  newsviz/pipeline.py
Labels: ROADMAP

#26 Выбор уровня агрегации по дате
  newsviz/visualizer/app.py
  newsviz/visualizer/utils.py
Labels: ROADMAP, hacktoberfest-accepted

#27 Iss22
  newsviz/visualizer/app.py
Labels: ROADMAP, hacktoberfest-accepted

#31 Шаблонный пайплайн: Тематизатор
  .gitignore
  config/config.ini
  newsviz/pipeline.py
  templates/make_tm.py
Labels: ROADMAP, hacktoberfest-accepted

#33 Add indexing
  config/config.ini
  newsviz/pipeline.py
  templates/make_tm.py
Labels: ROADMAP, hacktoberfest-accepted

#38 Save to ready2viz
  .gitignore
  config/config.ini
  newsviz/pipeline.py
Labels: ROADMAP

#39 add offset func and fix layout
  newsviz/visualizer/app.py
  newsviz/visualizer/utils.py
Labels: ROADMAP

#40 Давайте релизить уже
  .gitignore
  CONTRIBUTING.md
  README.md
  config/config.ini
  newsviz/pipeline.py
  newsviz/preprocessing_tools.py
  newsviz/topic_model.py
  newsviz/visualizer/app.py
  newsviz/visualizer/utils.py
  requirements.txt
  templates/make_tm.py
Labels: ROADMAP

#45 added missing punctuation
  newsviz/preprocessing_tools.py
Labels: ROADMAP
